build:
  docker:
    web: Dockerfile

run:
  web: npm run dev

stack: container

services:
  - name: database
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 40s
      retries: 10
      start_period: 10s

  - name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - database
    ports:
      - '3031:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  database:
  pgadmin-data:
